version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET_KEY=Bm2yOs7bSR7wwJUF3ZlJDf8b460/DZKEDRa1UiPPx2IutqE9FQB3ERrWzngSjqvu
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./src/main/resources/UI/personal-finance-tracker-two-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge