
spring:
  application:
    name: personal-finance-tracker-two
  datasource:
    url: jdbc:mysql://personal-finance-tracker-db.c6jo8igqw84t.us-east-1.rds.amazonaws.com:3306/personal_finance_tracker_two_db?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: Geisold13
    password: geballer1313B
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: auto
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: errormessages
  docker:
    compose:
      enabled: false


logging:
  level:
    org:
      springframework:
        security: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health